name: hungerz_ordering
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.8+9

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.3
  animation_wrappers: ^3.0.0
  flutter_bloc: ^8.0.1
  flutter_phoenix: ^1.0.0
  shared_preferences: ^2.2.3
  equatable: ^2.0.7
  http: ^1.4.0
  socket_io_client: ^3.1.2
  
  mobile_scanner: ^7.0.0
  permission_handler: ^12.0.0+1
  # buy_this_app:
  #   git:
  #     url: git@gitlab.com:verbosetech-flutter/buy-this-app-package.git
  #     ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.0"



flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/appicon.png"

flutter_launcher_name:
  name: "Hungerz eMenu"

flutter:
  uses-material-design: true

  assets:
    - assets/ItemCategory/
    - assets/
    - assets/food items/

  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans-Bold.ttf
        - asset: assets/fonts/ProductSans-Regular.ttf

