name: hungerz
description: A new Flutter application.

publish_to: 'none'
version: 1.0.8+9

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  geolocator: ^11.0.0 
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.2.0
  permission_handler: ^11.0.1
  # Vérifiez la dernière version sur pub.dev
  geocoding: ^2.1.1   # Vérifiez la dernière version sur pub.dev  
  flutter_lints: ^5.0.0
  flutter_dotenv: ^5.2.1
  dio: ^5.8.0+1
  flutter_stripe: ^11.5.0
  flutter_rating_bar: ^4.0.1
  google_maps_flutter: ^2.12.1   
  cupertino_icons: ^1.0.3
  flutter_phoenix: ^1.0.0
  country_code_picker: ^3.0.0
  google_places_flutter: ^2.1.0
  google_sign_in: ^5.0.0
  google_fonts: ^6.2.1
  flutter_bloc: ^9.1.0
  socket_io_client: ^2.0.0
  
  animation_wrappers: ^3.0.0
  flutter_polyline_points: ^2.1.0
  equatable: ^2.0.3
  shared_preferences: ^2.2.3
  url_launcher: ^6.0.20
  bloc: ^9.0.0
  http: ^1.3.0
  flutter_secure_storage: ^9.2.4
  collection: ^1.19.1
  intl: ^0.19.0
  # buy_this_app:
  #   git:
  #     url: git@gitlab.com:verbosetech-flutter/buy-this-app-package.git
  #     ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "images/icon.png"

flutter_launcher_name:
  name: "Hungerz"

flutter:

  uses-material-design: true
  fonts:
    - family: ProductSans
      fonts:
        - asset: fonts/ProductSans-Regular.ttf
        - asset: fonts/ProductSans-Bold.ttf
  assets:
    - .env
    - images/
    - images/footermenu/
    - images/account/
    - images/address/
    - images/icons/
    - images/payment/
    - images/Restaurants/
    - images/Banners/
    - images/Categories/
    - images/Food images/

